# This workflow will do a clean install of node dependencies and build the application across different versions of node
# It creates a thunderbird add-on XPI file from it and stores it as artifact

name: Nightly build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # first get the current timestamp for later use in the artifact filename
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.gettime.outputs.now }}
    steps:
    - id: gettime
      run: |
        d=$(date +%s)
        echo "::set-output name=now::$d"
  # now create the build files
  build:
    runs-on: ubuntu-latest
    needs: [timestamp]
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get current package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Get assumed next version
      id: semvers
      uses: WyriHaximus/github-action-next-semvers@v1
      with:
        version: ${{ steps.package-version.outputs.current-version }}
    - name: Build app using Yarn
      run: |
        npm install -g yarn
        yarn install
        yarn build
    - name: Create Thunderbird add-on (.xpi)
      shell: bash
      run: |
        cd dist/
        zip -q -r ../third-stats_${{ steps.semvers.outputs.v_minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi ./
    - name: Upload add-on nightly build artifact
      uses: actions/upload-artifact@v2
      with:
        name: third-stats-nightly
        path: third-stats_${{ steps.semvers.outputs.v_minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi
    - name: Push add-on to CDN
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CDN_HOST }}
        username: ${{ secrets.CDN_USER }}
        password: ${{ secrets.CDN_PASS }}
        port: ${{ secrets.CDN_PORT }}
        source: "third-stats_${{ steps.semvers.outputs.v_minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi"
        target: "${{ secrets.CDN_PATH }}/"
