# This workflow will do a clean install of node dependencies and build the application across different versions of node
# It creates a thunderbird add-on XPI file from it and stores it as artifact

name: Nightly build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # first get the current timestamp for later use in the artifact filename
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.gettime.outputs.now }}
    steps:
    - id: gettime
      run: |
        d=$(date +%s)
        echo "::set-output name=now::$d"
  # now create the build files
  build:
    runs-on: ubuntu-latest
    needs: [timestamp]
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Version
      id: version
      run: |
        patch=${GITHUB_REF#*refs/*/}
        echo ::set-output name=minor::${patch%.*}
    - name: Build app using Yarn
      run: |
        npm install -g yarn
        yarn install
        yarn build
    - name: Create Thunderbird add-on (.xpi)
      shell: bash
      run: |
        cd dist/
        zip -q -r ../third-stats_${{ steps.version.outputs.minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi ./
    - name: Upload add-on nightly build artifact
      uses: actions/upload-artifact@v2
      with:
        name: third-stats-nightly
        path: third-stats_${{ steps.version.outputs.minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi
    - name: Push add-on to CDN
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.CDN_HOST }}
        port: ${{ secrets.CDN_PORT }}
        username: ${{ secrets.CDN_USER }}
        password: ${{ secrets.CDN_PASS }}
        scp_source: third-stats_${{ steps.version.outputs.minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi
        scp_target: ${{ secrets.CDN_PATH }}/
