# This workflow will do a clean install of node dependencies and build the application across different versions of node
# It creates a thunderbird add-on .xpi file from it and stores it as artifact

name: Nightly build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # create the build files and push them to CDN
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Timestamp
      id: timestamp
      run: |
        echo "Creating current timestamp"
        d=$(date +%s)
        echo ::set-output name=now::${d}
    - name: Get Version
      id: version
      run: |
        PACKAGE_JSON_PATH="${1-.}"
        echo "Reading package.json from ${PACKAGE_JSON_PATH}/package.json"
        patch=v$(cat ${PACKAGE_JSON_PATH}/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
        echo "Got version ${patch}. Now increment it!"
        [[ ${patch::-2} =~ ([^0-9].*)([0-9]+) ]]
        next="${BASH_REMATCH[1]}$(( ${BASH_REMATCH[2]} + 1 ))"
        echo "Assumed next version is ${next}"
        echo ::set-output name=next::${next}
    - name: Build filename
      id: file
      run: |
        filename=third-stats_${{ steps.version.outputs.next }}-alpha.${{steps.timestamp.outputs.now}}.xpi
        echo "Build filename ${filename}"
        echo ::set-output name=name::${filename}
    - name: Build app using Yarn
      run: |
        npm install -g yarn
        yarn install
        yarn build
    - name: Create Thunderbird add-on (.xpi)
      shell: bash
      run: |
        cd dist/
        zip -q -r ../${{ steps.file.outputs.name }} ./
    - name: Upload add-on nightly build artifact
      uses: actions/upload-artifact@v2
      with:
        name: third-stats-nightly
        path: ${{ steps.file.outputs.name }}
    - name: Push add-on to CDN
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.CDN_HOST }}
        port: ${{ secrets.CDN_PORT }}
        username: ${{ secrets.CDN_USER }}
        password: ${{ secrets.CDN_PASS }}
        scp_source: ${{ steps.file.outputs.name }}
        scp_target: ${{ secrets.CDN_PATH }}/
