# This workflow will do a clean install of node dependencies and build the application across different versions of node
# It creates a thunderbird add-on XPI file from it and stores it as artifact

name: Nightly build with Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.gettime.outputs.now }}
    steps:
    - id: gettime
      run: |
        d=$(date +%s)
        echo "::set-output name=now::$d"
  build:
    runs-on: ubuntu-latest
    needs: [timestamp]
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get Version
      id: version
      uses: battila7/get-version-action@v2
    - name: Get next version
      id: semvers
      uses: WyriHaximus/github-action-next-semvers@v1
      with:
        version: ${{ steps.version.outputs.version-without-v }}
    - run: |
        npm install -g yarn
        yarn install
        yarn build
    - name: Build XPI file
      shell: bash
      run: |
        cd dist/
        zip -q -r ../third-stats_${{ steps.semvers.outputs.v_minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi ./
    - name: Upload add-on nightly build artifact
      uses: actions/upload-artifact@v2
      with:
        name: third-stats-nightly
        path: third-stats_${{ steps.semvers.outputs.v_minor }}-alpha.${{needs.timestamp.outputs.timestamp}}.xpi
